general {
    gaps_in = 0
    gaps_out = 0 
    border_size = 2
    col.active_border = rgb(e8e8e8)
    col.inactive_border = rgb(1e1e1e)
    col.nogroup_border = rgb(2a2a2a)
    col.nogroup_border_active = rgb(808080) 
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}
