windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = floating-kitty
    match:class = ^floating_kitty$
    float = yes
    size = 900 520
    center = yes
    opacity = 0.80 0.60
}

windowrule {
    name = pavucontrol-floating
    match:class = ^org\.pulseaudio\.pavucontrol$
    float = yes
    size = 800 600
    center = yes
}

windowrule {
    name = nwg-look-floating
    match:class = ^nwg-look$
    float = yes
    size = 600 500
    center = yes
}
