loop-file=inf

vo=gpu
hwdec=auto
autofit-larger=90%x90%
osc=yes
stop-screensaver=yes

ao=alsa
user-agent=Mozilla/5.0

cache=yes
demuxer-max-bytes=150MiB

slang=en,sr,hr,bs
alang=sr,en

sub-codepage=utf8
sub-scale-with-window=no
sub-font-size=48
sub-color=1/1/0
