animations {
    enabled = true
    bezier = fluid,  0.23, 1, 0.32, 1
    bezier = linear, 0,    0, 1,    1
    animation = windows,    1, 0.4,  fluid
    animation = windowsIn,  1, 0.4,  fluid,  popin 90%
    animation = windowsOut, 1, 0.25, linear, popin 90%
    animation = border,     0, 0,    default
    animation = fade,       1, 0.3,  fluid
    animation = fadeOut,    1, 0.2,  linear
    animation = workspaces,    0, 0, default
    animation = workspacesIn,  0, 0, default
    animation = workspacesOut, 0, 0, default
}
